spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    hikari: 54
    maxLifeTime: 43200000
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  application:
    name: user

server:
  port: 8081

dis:
  app:
    jwtSecret: jwtDisSecretKey
    jwtExpiration: 86400

  spring:
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2000KB
        max-file-size: 15MB
        max-request-size: 25MB
SchedulingJob:
  enrollment-update-delay: PT5S
